Features/s3 handler
macrocosm-os/atom pull request #19
Opened 2024-12-23 16:00 UTC by schampoux

- Adds a customizable s3 handler to atom.

2024-12-23 16:13 UTC, mccrindlebrian requested changes

2024-12-23 16:13 UTC, mccrindlebrian commented on atom/handlers/handler.py
> +        location: str,
would be nice to be more specific: 

```
local_filepath: str, 
s3_bucket_location:str
```

2024-12-23 16:13 UTC, mccrindlebrian commented on atom/handlers/handler.py
> +            key = f"{location}/{file_name}"
```suggestion
            key = os.path.join(s3_bucket_location, filename)
```

2024-12-23 16:13 UTC, mccrindlebrian commented on atom/handlers/s3_client.py
> +class S3Client:
How is this class created when using `folding`? It takes the Literal string of the _secret_ access key? How is this secure?

2024-12-23 16:17 UTC, schampoux commented on atom/handlers/s3_client.py
> +class S3Client:
in folding its instantiated using environment variables as the respective arguments.

2024-12-23 16:22 UTC, mccrindlebrian commented on atom/handlers/handler.py
> +            )
maybe we shouldn't be printing codes here, but rather returning a boolean if it was successful / failed. So the base class in `BaseHandler` indicates this

2024-12-23 16:25 UTC, mccrindlebrian reviewed
comment

2025-01-02 19:44 UTC, steffencruz commented on atom/handlers/s3_client.py
> +class S3Client:
what's the benefit of having a long-lived connection to a remote S3 as a python class? The class is literally just a single command

2025-01-02 20:04 UTC, schampoux commented on atom/handlers/s3_client.py
> +class S3Client:
The intention was to reduce redundancy i.e. for reuse wherever s3 interactions are required. Also because the client is intended to be useful with all s3 providers.

2025-01-02 20:54 UTC, schampoux commented on atom/handlers/handler.py
> +            )
removed print statements in recent commit

2025-01-03 00:15 UTC, mccrindlebrian commented on atom/handlers/s3_client.py
> +    "secret_access_key": os.getenv("S3_SECRET"),
we need to have docs on how to generate this properly

2025-01-03 00:19 UTC, mccrindlebrian requested changes

2025-01-03 00:19 UTC, mccrindlebrian commented on atom/handlers/s3_client.py
> +class S3Client:
I agree with Steffen here - this doesn't need to be a class. I would recommend making this into a function that returns the instance of the client

2025-01-03 00:19 UTC, mccrindlebrian commented on tests/test_s3.py
> +    assert client.s3_client == mock_s3
this test would also need to change

2025-01-03 00:35 UTC, schampoux commented on atom/handlers/s3_client.py
> +    "secret_access_key": os.getenv("S3_SECRET"),
addressed in commit

2025-01-03 00:35 UTC, schampoux commented on tests/test_s3.py
> +    assert client.s3_client == mock_s3
addressed in commit

2025-01-03 01:01 UTC, mccrindlebrian commented on README.md
> +- `S3_SECRET`: Your S3 secret access key.
move this to the README level of the handlers

2025-01-03 01:03 UTC, mccrindlebrian requested changes

2025-01-03 01:03 UTC, mccrindlebrian commented on atom/handlers/handler.py
> +def create_s3_client(region_name: str, endpoint_url: str, access_key_id: str, secret_access_key: str):
```suggestion
def create_s3_client(region_name: str, endpoint_url: str, access_key_id: str, secret_access_key: str) -> boto3.client:
```

2025-01-03 01:03 UTC, mccrindlebrian commented
After the changes and making sure the typing does not throw an error, this LGTM!

2025-01-03 16:25 UTC, schampoux commented on README.md
> +- `S3_SECRET`: Your S3 secret access key.
cone

2025-01-03 16:39 UTC, mccrindlebrian approved these changes

2025-01-03 16:46 UTC, merged